-- [Previous 70 tools remain exactly the same, continuing with new tools...]

-- 71. Airtable
('Airtable', 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=128&h=128&fit=crop',
'Collaborative database platform',
'Howie Liu',
'["Database views", "Automation", "API access", "Integrations", "Templates"]'::jsonb,
'{"startingPrice": "$10", "hasFreeplan": true, "pricingModel": "per-user"}'::jsonb,
'https://airtable.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=1200&h=800&fit=crop"]'::jsonb,
'1. Create base\n2. Design tables\n3. Add views\n4. Share workspace',
'["Flexible views", "Easy to use", "Rich features", "Templates"]'::jsonb,
'["API limits", "Storage limits", "Premium features"]'::jsonb,
'["Project managers", "Content teams", "Startups"]'::jsonb,
'Productivity'),

-- 72. New Relic
('New Relic', 'https://images.unsplash.com/photo-1611162616935-fc2a5489a232?w=128&h=128&fit=crop',
'Application monitoring platform',
'Lew Cirne',
'["APM", "Infrastructure monitoring", "Browser monitoring", "Analytics", "Alerts"]'::jsonb,
'{"startingPrice": "$99", "hasFreeplan": true, "pricingModel": "usage-based"}'::jsonb,
'https://newrelic.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616935-fc2a5489a232?w=1200&h=800&fit=crop"]'::jsonb,
'1. Install agent\n2. Configure monitoring\n3. Set up dashboards\n4. Create alerts',
'["Comprehensive monitoring", "Good UI", "Detailed metrics", "Integration"]'::jsonb,
'["Complex pricing", "Data retention", "Learning curve"]'::jsonb,
'["DevOps teams", "SRE teams", "Enterprise"]'::jsonb,
'Analytics'),

-- 73. Twilio
('Twilio', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=128&h=128&fit=crop',
'Communication API platform',
'Jeff Lawson',
'["SMS", "Voice", "Video", "Authentication", "Email"]'::jsonb,
'{"startingPrice": "$0", "hasFreeplan": true, "pricingModel": "usage-based"}'::jsonb,
'https://twilio.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=800&fit=crop"]'::jsonb,
'1. Create account\n2. Get credentials\n3. Choose API\n4. Implement features',
'["Reliable", "Good documentation", "Many features", "Global reach"]'::jsonb,
'["Complex pricing", "Technical setup", "Support cost"]'::jsonb,
'["Developers", "Enterprise", "Communication apps"]'::jsonb,
'Development'),

-- 74. Calendly
('Calendly', 'https://images.unsplash.com/photo-1611162616677-5b6bd52b8e37?w=128&h=128&fit=crop',
'Scheduling platform',
'Tope Awotona',
'["Automated scheduling", "Calendar sync", "Team scheduling", "Integrations", "Analytics"]'::jsonb,
'{"startingPrice": "$8", "hasFreeplan": true, "pricingModel": "per-user"}'::jsonb,
'https://calendly.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616677-5b6bd52b8e37?w=1200&h=800&fit=crop"]'::jsonb,
'1. Connect calendar\n2. Set availability\n3. Create events\n4. Share link',
'["Easy to use", "Time zone handling", "Integration options", "Professional"]'::jsonb,
'["Limited free plan", "Branding options", "Advanced features cost"]'::jsonb,
'["Professionals", "Sales teams", "Consultants"]'::jsonb,
'Productivity'),

-- 75. Algolia
('Algolia', 'https://images.unsplash.com/photo-1611162616305-c69b3037f77d?w=128&h=128&fit=crop',
'Search API platform',
'Nicolas Dessaigne',
'["Search API", "Analytics", "Personalization", "A/B testing", "UI libraries"]'::jsonb,
'{"startingPrice": "$29", "hasFreeplan": true, "pricingModel": "usage-based"}'::jsonb,
'https://algolia.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616305-c69b3037f77d?w=1200&h=800&fit=crop"]'::jsonb,
'1. Create index\n2. Upload data\n3. Configure search\n4. Implement UI',
'["Fast search", "Easy setup", "Good documentation", "Analytics"]'::jsonb,
'["Premium features", "Complex pricing", "Data limits"]'::jsonb,
'["E-commerce", "Content sites", "Mobile apps"]'::jsonb,
'Development'),

-- 76. LaunchDarkly
('LaunchDarkly', 'https://images.unsplash.com/photo-1611162617263-4ec3060a058e?w=128&h=128&fit=crop',
'Feature management platform',
'Edith Harbaugh',
'["Feature flags", "A/B testing", "User targeting", "Analytics", "SDKs"]'::jsonb,
'{"startingPrice": "$75", "hasFreeplan": false, "pricingModel": "tiered"}'::jsonb,
'https://launchdarkly.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162617263-4ec3060a058e?w=1200&h=800&fit=crop"]'::jsonb,
'1. Create flags\n2. Set targeting\n3. Roll out features\n4. Monitor impact',
'["Easy rollouts", "Good SDKs", "Enterprise ready", "Monitoring"]'::jsonb,
'["Expensive", "Complex setup", "Learning curve"]'::jsonb,
'["Development teams", "Product teams", "Enterprise"]'::jsonb,
'Development'),

-- 77. Mixpanel
('Mixpanel', 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=128&h=128&fit=crop',
'Product analytics platform',
'Suhail Doshi',
'["User analytics", "Funnel analysis", "Retention", "A/B testing", "Segmentation"]'::jsonb,
'{"startingPrice": "$25", "hasFreeplan": true, "pricingModel": "event-based"}'::jsonb,
'https://mixpanel.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=1200&h=800&fit=crop"]'::jsonb,
'1. Add tracking\n2. Create reports\n3. Build funnels\n4. Analyze data',
'["Detailed analytics", "Good UI", "Custom reports", "API access"]'::jsonb,
'["Learning curve", "Data limits", "Complex pricing"]'::jsonb,
'["Product teams", "Marketing teams", "Analytics teams"]'::jsonb,
'Analytics'),

-- 78. Contentful
('Contentful', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=128&h=128&fit=crop',
'Headless CMS platform',
'Sascha Konietzke',
'["Content modeling", "API-first", "Multi-language", "Asset management", "Workflows"]'::jsonb,
'{"startingPrice": "$489", "hasFreeplan": true, "pricingModel": "tiered"}'::jsonb,
'https://contentful.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=800&fit=crop"]'::jsonb,
'1. Create space\n2. Model content\n3. Add entries\n4. Integrate API',
'["Flexible", "Developer friendly", "Good APIs", "Scalable"]'::jsonb,
'["Expensive", "Technical setup", "Complex models"]'::jsonb,
'["Content teams", "Developers", "Enterprise"]'::jsonb,
'Development'),

-- 79. Okta
('Okta', 'https://images.unsplash.com/photo-1611162616677-5b6bd52b8e37?w=128&h=128&fit=crop',
'Identity management platform',
'Todd McKinnon',
'["SSO", "MFA", "User management", "Directory integration", "API access"]'::jsonb,
'{"startingPrice": "$2", "hasFreeplan": true, "pricingModel": "per-user"}'::jsonb,
'https://okta.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616677-5b6bd52b8e37?w=1200&h=800&fit=crop"]'::jsonb,
'1. Configure tenant\n2. Add applications\n3. Set up policies\n4. Deploy SSO',
'["Enterprise ready", "Compliance", "Integration options", "Security"]'::jsonb,
'["Complex setup", "Premium features", "Support cost"]'::jsonb,
'["Enterprise", "Security teams", "IT teams"]'::jsonb,
'Security'),

-- 80. Amplitude
('Amplitude', 'https://images.unsplash.com/photo-1611162618479-ee4b0cb6a633?w=128&h=128&fit=crop',
'Product analytics platform',
'Spenser Skates',
'["Behavioral analytics", "User paths", "Cohort analysis", "Experimentation", "Predictions"]'::jsonb,
'{"startingPrice": "$0", "hasFreeplan": true, "pricingModel": "event-based"}'::jsonb,
'https://amplitude.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162618479-ee4b0cb6a633?w=1200&h=800&fit=crop"]'::jsonb,
'1. Implement SDK\n2. Track events\n3. Create charts\n4. Share insights',
'["Deep insights", "Easy to use", "Good free tier", "Integration"]'::jsonb,
'["Enterprise costs", "Data sampling", "Feature limits"]'::jsonb,
'["Product teams", "Data teams", "Growth teams"]'::jsonb,
'Analytics'),

-- 81. Sentry
('Sentry', 'https://images.unsplash.com/photo-1611162616305-c69b3037f77d?w=128&h=128&fit=crop',
'Error monitoring platform',
'David Cramer',
'["Error tracking", "Performance monitoring", "Release tracking", "Source maps", "Integrations"]'::jsonb,
'{"startingPrice": "$26", "hasFreeplan": true, "pricingModel": "event-based"}'::jsonb,
'https://sentry.io',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616305-c69b3037f77d?w=1200&h=800&fit=crop"]'::jsonb,
'1. Add SDK\n2. Configure project\n3. Monitor errors\n4. Set up alerts',
'["Easy setup", "Good UI", "Many SDKs", "Integration options"]'::jsonb,
'["Event quotas", "Storage limits", "Premium features"]'::jsonb,
'["Developers", "DevOps teams", "QA teams"]'::jsonb,
'Development'),

-- 82. Intercom
('Intercom', 'https://images.unsplash.com/photo-1611162617263-4ec3060a058e?w=128&h=128&fit=crop',
'Customer messaging platform',
'Eoghan McCabe',
'["Live chat", "Chatbots", "Customer support", "Marketing automation", "Product tours"]'::jsonb,
'{"startingPrice": "$39", "hasFreeplan": false, "pricingModel": "per-seat"}'::jsonb,
'https://intercom.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162617263-4ec3060a058e?w=1200&h=800&fit=crop"]'::jsonb,
'1. Install messenger\n2. Set up inbox\n3. Create campaigns\n4. Configure bots',
'["Good UI", "Feature rich", "Integration options", "Analytics"]'::jsonb,
'["Expensive", "Complex pricing", "Feature overwhelm"]'::jsonb,
'["SaaS companies", "Support teams", "Marketing teams"]'::jsonb,
'Customer Support'),

-- 83. Optimizely
('Optimizely', 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=128&h=128&fit=crop',
'Experimentation platform',
'Dan Siroker',
'["A/B testing", "Feature flags", "Web experimentation", "Analytics", "Personalization"]'::jsonb,
'{"startingPrice": "$50", "hasFreeplan": false, "pricingModel": "tiered"}'::jsonb,
'https://optimizely.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=1200&h=800&fit=crop"]'::jsonb,
'1. Create experiment\n2. Set up variations\n3. Target audience\n4. Analyze results',
'["Statistical rigor", "Enterprise ready", "Integration options", "Features"]'::jsonb,
'["Expensive", "Complex setup", "Learning curve"]'::jsonb,
'["Marketing teams", "Product teams", "Enterprise"]'::jsonb,
'Marketing'),

-- 84. Retool
('Retool', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=128&h=128&fit=crop',
'Internal tools platform',
'David Hsu',
'["Drag-and-drop UI", "Database integration", "API connections", "Custom components", "Workflows"]'::jsonb,
'{"startingPrice": "$10", "hasFreeplan": true, "pricingModel": "per-user"}'::jsonb,
'https://retool.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=800&fit=crop"]'::jsonb,
'1. Connect data\n2. Build interface\n3. Add logic\n4. Deploy app',
'["Fast development", "Customizable", "Integration options", "Templates"]'::jsonb,
'["Learning curve", "Enterprise costs", "Limited components"]'::jsonb,
'["Developers", "Internal teams", "Startups"]'::jsonb,
'Development'),

-- 85. Vercel
('Vercel', 'https://images.unsplash.com/photo-1611162616677-5b6bd52b8e37?w=128&h=128&fit=crop',
'Frontend deployment platform',
'Guillermo Rauch',
'["Edge network", "Git integration", "Preview deployments", "Serverless functions", "Analytics"]'::jsonb,
'{"startingPrice": "$0", "hasFreeplan": true, "pricingModel": "tiered"}'::jsonb,
'https://vercel.com',
'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
'["https://images.unsplash.com/photo-1611162616677-5b6bd52b8e37?w=1200&h=800&fit=crop"]'::jsonb,
'1. Connect repo\n2. Configure project\n3. Deploy site\n4. Monitor performance',
'["Easy deployment", "Good performance", "Developer experience", "Integration"]'::jsonb,
'["Build limits", "Enterprise costs", "Premium features"]'::jsonb,
'["Frontend developers", "Next.js teams", "Startups"]'::jsonb,
'Development');